export const LIST_EXPERIENCES_DATA = [
  {
    position: 'Desenvolvedor Full-Stack',
    company: 'WPLAY - Marketing Interativo',
    location: 'Novo Hamburgo, RS',
    period: 'Set 2017 - Mai 2018',
    description:
      'Atuei como desenvolvedor Fullstack, com foco no backend utilizando um CMS proprietário baseado em CodeIgniter (PHP). Esse CMS era a base para o desenvolvimento de diversos sites entre eles sites governamentais e da indústria alimentícia, como Eliandro Alimentos e Prefeitura de Lemes.',
    activities: [
      'Desenvolvi sistemas web completos com Framework Codeigniter e MySQL',
      'Criei um CMS com o Framework Laravel e MySQL',
      'Desenvolvi sistemas web completos com Laravel e PHP',
      'Estruturei consultas SQL para relatórios de saúde',
    ],
    stacks: [
      'PHP',
      'Codeigniter',
      'Laravel',
      'MySQL',
      'PostgreSQL',
      'Javascript',
      'JQuery',
      'Git',
      'GitHub',
      'GitLab',
      'Linux',
      'Filezilla',
    ],
  },
  {
    position: 'Desenvolvedor Full-Stack Júnior',
    company: 'Compass UOL',
    location: 'Porto Alegre, RS',
    period: 'Jun 2018 - Dez 2019',
    description:
      'Atuei como desenvolvedor Fullstack no desenvolvimento de um sistema interno de gestão de perdas e avarias, com dashboard interativo, controle de acessos e registro de ocorrências integrado a SLA e fila de tickets. Implementei notificações automáticas por e-mail e atuei em todas as etapas do projeto, sendo responsável por 100% do frontend e backend, incluindo autenticação com JWT, integração com banco de dados e documentação com Swagger.',
    activities: [
      'Apoio na Sustentação do Projeto de Perdas e Roubo',
      'Desenvolvi interfaces responsivas com React.js',
      'Implementei microsserviços em NodeJS',
      'Utilizei Docker e Kubernetes para containerização',
    ],
    stacks: [
      'Javascript',
      'React.js',
      'Redux',
      'RBCA',
      'Redux Thunk',
      'Redux Saga',
      'Styled Component',
      'React Router DOM',
      'NodeJS',
      'Express',
      'Sequelize',
      'Swagger',
      'Oracle',
      'MongoDB',
      'Docker',
      'Kubernetes',
      'Git',
      'CI/CD',
      'Azure',
      'Graylog',
    ],
  },
  {
    position: 'Desenvolvedor Full-Stack Pleno',
    company: 'South System',
    location: 'Porto Alegre, RS',
    period: 'Dez 2019 - Fev 2024',
    description:
      'Atuei em projetos de grande escala, desenvolvendo soluções para sistemas corporativos, e-commerce e ERP, com foco em boas práticas, acessibilidade, testes automatizados e performance. Destaque para o desenvolvimento de sistemas completos (Angular, Node.js e Java Spring Boot), PWAs de e-commerce, interfaces complexas em React.js, além da criação de design systems e bibliotecas de componentes com documentação e integração a aplicações corporativas.',
    activities: [
      'Sistema de Gestão de Pessoas: desenvolvimento completo (frontend em Angular, BFF em Node.js/Express, backend em Java Spring Boot), com testes automatizados para assegurar confiabilidade',
      'PWAs de E-commerce (Marcas de Alimentação e Restaurantes): implementação de carrinho de compras, delivery e take-away, garantindo a operação digital durante a pandemia.',
      'Sistema Crítico Internacional: desenvolvimento de interfaces complexas em React.js, integração com APIs REST, formulários dinâmicos otimizados, Context API, Styled Components e testes unitários com Jest/RTL',
      'Design System Corporativo: criação de bibliotecas de componentes em React.js, assegurando padronização visual, escalabilidade e acessibilidade, com documentação no Storybook',
      'ERP Corporativo: desenvolvimento frontend com React.js, formulários dinâmicos, arquitetura de estado com reducers e integração total com Design System corporativo',
    ],
    stacks: [
      'Javascript',
      'Angular',
      'Java',
      'Spring Boot',
      'BFF',
      'React.js',
      'PWA',
      'Context API',
      'RBCA',
      'React Hook Form',
      'Zod',
      'Yup',
      'Storybook',
      'Styled Component',
      'React Router DOM',
      'NodeJS',
      'Gateway',
      'Express',
      'NestJS',
      'Sequelize',
      'Swagger',
      'PostgreSQL',
      'MongoDB',
      'Docker',
      'Jest',
      'React Testing Library',
      'Supertest',
      'Kubernetes',
      'Git',
      'CI/CD',
      'Azure',
      'Graylog',
    ],
  },
  {
    position: 'Desenvolvedor Full-Stack Sênior',
    company: 'CWI Software',
    location: 'Porto Alegre, RS',
    period: 'Jun 2024 - Jul 2025',
    description:
      'Atuei em projetos de grande visibilidade e impacto, desenvolvendo soluções digitais para landing pages corporativas, blogs, APIs e sistemas internos, sempre com foco em SEO, acessibilidade, performance, design system e escalabilidade.',
    activities: [
      'Landing Page Apple & Black Friday Campaigns: desenvolvimento em Next.js com arquitetura de microfrontends, páginas 100% otimizadas para SEO, acessibilidade, performance validada pelo Lighthouse, componentes funcionais resilientes (FAQs/accordions/tabs) e DataLayer para analytics',
      'Blog Corporativo WordPress: criação de um tema WordPress do zero, alinhado ao Design System e protótipos do Figma, com foco em SEO, performance, acessibilidade, componentes resilientes e infraestrutura otimizada com Docker/MySQL',
      'Otimização de API em Laravel: redução do tempo de processamento de arquivos de 12 horas para 14 minutos por meio da refatoração de filas e inserções em lote, aumentando escalabilidade e eficiência do sistema',
      'Criação de aplicativo MovieFilms',
    ],
    stacks: [
      'Dart',
      'Flutter',
      'PHP',
      'Wordpress',
      'Laravel',
      'BFF',
      'React.js',
      'Next.js',
      'Context API',
      'RBCA',
      'React Hook Form',
      'Zod',
      'Storybook',
      'Styled Component',
      'React Router DOM',
      'NodeJS',
      'Gateway',
      'Express',
      'Sequelize',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'Swagger',
      'Jest',
      'React Testing Library',
      'Supertest',
      'Docker',
      'Kubernetes',
      'Git',
      'CI/CD',
      'Azure',
    ],
  },
  {
    position: 'Desenvolvedor Full-Stack',
    company: 'Datum',
    location: 'Porto Alegre, RS',
    period: 'Out 2025 - Atual',
    description:
      'Desenvolvedor Frontend atuando com React.js em sistemas do agronegócio, com foco em manipulação de dados geoespaciais via Google Maps. Experiência em manutenção e evolução de sistemas legados, priorizando performance, escalabilidade e qualidade de código em um ambiente de alta complexidade.',
    activities: [
      'Gerenciamento e Manipulação de Mapa do Google com talhões',
      'Trabalhando com sistema legado usando CRA',
    ],
    stacks: [
      'React.js',
      'Context API',
      'RBCA',
      'React Hook Form',
      'Zod',
      'Styled Component',
      'React Router DOM',
      'NodeJS',
      'Express',
      'Sequelize',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'Swagger',
      'Docker',
      'Kubernetes',
      'Git',
      'CI/CD',
      'Azure',
      'Git/Github',
    ],
  },
]
